// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3zzvu8R8xYyKvT59OK7twnXWroSUC-ys',
    appId: '1:833673625104:web:498afb0e1f741e3cc59495',
    messagingSenderId: '833673625104',
    projectId: 'habit-tracker-app-844d4',
    authDomain: 'habit-tracker-app-844d4.firebaseapp.com',
    storageBucket: 'habit-tracker-app-844d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapnBJ20-moV2wlhqB_jmJL5gkdEII3SA',
    appId: '1:833673625104:android:87d4faa46e35fe5fc59495',
    messagingSenderId: '833673625104',
    projectId: 'habit-tracker-app-844d4',
    storageBucket: 'habit-tracker-app-844d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSgKDlB8mbe2KkeuvGFYISSmhT6FUo3RQ',
    appId: '1:833673625104:ios:fb8a1d69f918cf66c59495',
    messagingSenderId: '833673625104',
    projectId: 'habit-tracker-app-844d4',
    storageBucket: 'habit-tracker-app-844d4.appspot.com',
    iosClientId:
        '833673625104-7e838pgmjvs9is096ked82mnonslhadu.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSgKDlB8mbe2KkeuvGFYISSmhT6FUo3RQ',
    appId: '1:833673625104:ios:fb8a1d69f918cf66c59495',
    messagingSenderId: '833673625104',
    projectId: 'habit-tracker-app-844d4',
    storageBucket: 'habit-tracker-app-844d4.appspot.com',
    iosClientId:
        '833673625104-7e838pgmjvs9is096ked82mnonslhadu.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );
}
